name: "PR Validate"
description: "Validate Pull Request metadata like Conventional Commits and fork rules"
branding:
  icon: "check-circle"
  color: "blue"

inputs:
  conventional_commits:
    description: "Enforce conventional commits?"
    default: "true"
  reject_forks:
    description: "Reject forks? [true|false]"
    default: "true"

runs:
  using: "composite"
  steps:
    - name: Fork Check
      if: inputs.reject_forks == 'true' && github.event.pull_request.head.repo.fork
      shell: bash
      run: |
        echo "::error::We do not accept pull requests directly from forks. Please push your changes to a new branch directly on the target repository, and open a new PR from there."
        exit 1

    - name: Conventional Commits
      if: inputs.conventional_commits != 'false'
      id: semantic
      uses: amannn/action-semantic-pull-request@48f256284bd46cdaab1048c3721360e808335d50 # v6.1.1
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Conventional Commits Instructions
      if: failure() && steps.semantic.outcome == 'failure'
      shell: bash
      run: |
        echo "::error::Title validation failed. Please edit the PR title at the top of the page to match Conventional Commits (e.g. 'feat: ...', 'fix: ...'). This job will automatically re-run as soon as you save the new title—no manual retry needed! See https://www.conventionalcommits.org/"
