name: .Image Promotion

on:
  workflow_call:
    inputs:
      packages:
        description: "Space-separated list of packages to promote"
        required: true
        type: string
      target:
        description: "Target tag (e.g. PR number, test or prod)"
        required: true
        type: string
      tag_promote:
        description: "New tag to apply (e.g. latest, test, prod)"
        default: latest
        required: false
        type: string
      organization:
        description: "GitHub organization"
        default: ${{ github.repository_owner }}
        required: false
        type: string
      repository:
        description: "GitHub repository name"
        default: ${{ github.event.repository.name }}
        required: false
        type: string
      merge_branch:
        description: "Merge target branch"
        required: false
        type: string
        default: ${{ github.event.repository.default_branch }}

permissions: {}

jobs:
  vars:
    runs-on: ubuntu-24.04
    outputs:
      packages: ${{ steps.packages.outputs.packages }}
    steps:
      - id: packages
        shell: bash
        env:
          PACKAGES: ${{ inputs.packages }}
        run: |
          read -r -a pkgs <<< "$PACKAGES"
          echo "packages=$(jq -cn '$ARGS.positional' --args "${pkgs[@]}")" >> "$GITHUB_OUTPUT"

  retags:
    name: Retag Image
    needs: vars
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == inputs.merge_branch
    runs-on: ubuntu-24.04
    permissions:
      packages: write
    strategy:
      matrix:
        package: ${{ fromJson(needs.vars.outputs.packages) }}
    steps:
      - uses: shrink/actions-docker-registry-tag@e6aaef25c595b6e0edd18bf4c7dbfea3abd43299 # v5
        with:
          registry: ghcr.io
          repository: ${{ inputs.organization }}/${{ inputs.repository }}/${{ matrix.package }}
          target: ${{ inputs.target }}
          tags: ${{ inputs.tag_promote }}
