name: PR Validate

on:
  pull_request:
    types: [edited, opened, synchronize, reopened, ready_for_review]

concurrency:
  group: ${{ github.workflow }}-edit-${{ github.event.number }}
  cancel-in-progress: true

permissions: {}

jobs:
  validate:
    name: Validate PR
    if: (! github.event.pull_request.draft)
    permissions:
      contents: read
      pull-requests: write
    uses: $/.github/workflows/.pr-validate.yml
