name: Test PR Validate

on:
  workflow_call:
  workflow_dispatch:

permissions: {}

jobs:
  test-default:
    name: Test Default Inputs
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      pull-requests: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run pr-validate
        uses: $/pr-validate
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          conventional_commits: false
          reject_forks: false
